# Generated by Django 3.2.7 on 2021-09-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('upload_file', models.FileField(upload_to='portal/client_cv/')),
            ],
        ),
        migrations.CreateModel(
            name='JobDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('responsibilities', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_details', models.ManyToManyField(blank=True, related_name='job_client_details', to='career.ClientDetails')),
            ],
        ),
    ]
