# Generated by Django 3.2.7 on 2021-09-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescriptions',
            old_name='requirements',
            new_name='qualification',
        ),
        migrations.RemoveField(
            model_name='jobdescriptions',
            name='responsibilities',
        ),
        migrations.AddField(
            model_name='jobdescriptions',
            name='employment_type',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
